# Generated by Django 4.2.3 on 2023-07-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.filmtype', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='page',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/&Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
